# -*- coding: utf-8 -*-
"""project_economics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqFOgnpLqGwqzWj8idPsKC4MzDPn37wk
"""

import plotly.express as px
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel("/content/Current-macroeconomic-situation-Tables-Based-on-Six-Month-data-of-2082.83.xlsx", sheet_name = 16,header=None)


df.head(10)

df = df.drop(columns =[0])

df = df.iloc[7:].reset_index(drop=True) #removing 1 to 6 th rows
df = df.iloc[:-4].reset_index(drop=True)

# replacing - with nan
df = df.replace('-', np.nan)
df.head()

df.shape

print(df.columns)

print(len(df))

df.columns = [
    'S.N.',
    'Commodities',
    '2023/24 Annual',
    '2023/24 Six Months',
    '2024/25 Annual',
    '2024/25 Six Months',
    '2025/26 Six Months',
    '2024/25 Growth %',
    '2025/26 Growth %'
]
df.head()

highest = df.loc[df["2023/24 Annual"].idxmax()]
print(highest)

lowest = df.loc[df["2024/25 Annual"].idxmin()]
print(lowest)

df.describe()

# checking empty data or data handling
print(df.isnull().sum())

# checking du-plicates data
print(df.duplicated().sum())

"""The bar chart sh"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))

plt.bar(df["Commodities"], df["2023/24 Annual"])

plt.xlabel("Commodity")
plt.ylabel("Export Value")
plt.title("Export Value by Commodity of 2023/24")

plt.xticks(rotation=90)
plt.tight_layout()

plt.show()

"""Zinch Sheet had the highest export value during 2023/24, followed by polyster yarn, while fruits accounted
for a comparatively smaller share of imports. The differences in bar heights indicate that import values varied substantially across commodities.
"""

plt.figure(figsize = (12,6))

plt.bar(df["Commodities"], df["2024/25 Annual"])

plt.xlabel("Commodity")
plt.ylabel("Export Value")
plt.title("Export Value by Commodity of 2024/25")

plt.xticks(rotation = 90)
plt.tight_layout()

"""Bar Chart Show Soyabean oil is the largest export commodity in 2024/25 year."""

# checking empty data or data handling
print(df.isnull().sum())

# checking du-plicates data
print(df.duplicated().sum())

# select the 10 rows with largest value in column 3
top10 = df.nlargest(10, "2024/25 Annual")
# create a figure with a width of 10 inches and height 0f 6 inches
plt.figure(figsize = (10, 6))

# create a bar chart
# x -axis: comodity names (columns 2)
# y-axis:Values(column(3))
plt.bar(top10["Commodities"], top10["2024/25 Annual"])

plt.xlabel("Commodity")
plt.ylabel("Value")
plt.title("Top 10 Commodities 2024/25 Annual")

plt.xticks(rotation=45, ha="right")
plt.tight_layout()

plt.show()

print(top10)

import numpy as np
import matplotlib.pyplot as plt

df_annual = top10[['Commodities', '2023/24 Annual', '2024/25 Annual']]

labels = df_annual['Commodities'].tolist()
x = np.arange(len(labels))
width = 0.4

fig, ax = plt.subplots(figsize=(10,6))

ax.bar(x - width/2, df_annual['2023/24 Annual'], width, label='2023/24')
ax.bar(x + width/2, df_annual['2024/25 Annual'], width, label='2024/25')

ax.set_xticks(x)
ax.set_xticklabels(labels, rotation=45, ha='right')

ax.set_ylabel("Annual Value")
ax.set_title("Top 10 Commodities - Annual Comparison")
ax.legend()

plt.tight_layout()
plt.show()

"""These above shows the top 10 commodities of 2024/25 Annual."""

plt.figure(figsize =(12,6))
plt.plot(df["Commodities"], df["2023/24 Annual"])
plt.plot(df["Commodities"], df["2024/25 Annual"])

plt.xticks(rotation=90, ha="right")
plt.tight_layout()

plt.show()

top5 = df.nlargest(5, "2024/25 Annual")

plt.figure(figsize=(8,8))

plt.pie(
    top5["2024/25 Annual"],
    labels=top5["Commodities"],
    autopct="%1.1f%%",
)
plt.title("Percentage of Commodities(2024/25)")

plt.show()

"""Soyabean has highest export percentage among top5"""

plt.scatter(df.index, df["2023/24 Annual"], color="blue", label="2023/24")
plt.scatter(df.index, df["2024/25 Annual"], color="green", label="2024/25")

plt.xlabel("Commodities Index")
plt.ylabel("Value")
plt.title("Year-wise Comparison")
plt.legend()
plt.show()



plt.hist(df["2024/25 Annual"], bins=10, alpha=0.5, label="2024/25 Six Months")
plt.hist(df["2023/24 Annual"], bins=10, alpha=0.5, label="2025/26 Six Months")

plt.title("Distribution of Values")
plt.xlabel("Export Value")
plt.ylabel("Frequency")

plt.legend()

plt.show()

plt.hist(df["2023/24 Six Months"], bins=10, alpha=0.5, label="2023/24 Six Months")
plt.hist(df["2024/25 Six Months"], bins=10, alpha=0.5, label="2024/25 Six Months")
plt.hist(df["2025/26 Six Months"], bins=10, alpha=0.5, label="2025/26 Six Months")

plt.title("Distribution of Values")
plt.xlabel("Export Value")
plt.ylabel("Frequency")

plt.legend()

plt.show()

import matplotlib
print(matplotlib.__version__)
top5 = df.nlargest(5, "2024/25 Annual")

species = tuple(top5['Commodities'])

penguin_means = {
    '2024/25 Annual': tuple(top5['2024/25 Annual']),
    '2023/24 Annual': tuple(top5['2023/24 Annual']),
}

fig, ax = plt.subplots(layout='constrained')

res = ax.grouped_bar(penguin_means, tick_labels=species, group_spacing=1)

for container in res.bar_containers:
    ax.bar_label(container, padding=3)

ax.set_ylabel('Value')
ax.set_title('Top 5 Commodities')
ax.legend(loc='upper left', ncols=3)

plt.show()

df[["2023/24 Annual", "2024/25 Annual"]].plot(kind="box")

# checking empty data or data handling
print(df.isnull().sum())

# checking du-plicates data
print(df.duplicated().sum())

# checking empty data or data handling
print(df.isnull().sum())

# checking du-plicates data
print(df.duplicated().sum())

# checking empty data or data handling
print(df.isnull().sum())

# checking du-plicates data
print(df.duplicated().sum())

# checking empty data or data handling
print(df.isnull().sum())

# checking du-plicates data
print(df.duplicated().sum())

top5_export_2023_2024 = df.nlargest(5, '2023/24 Annual')[['Product', '2023/24 Annual']]
print(top5_export_2023_2024)

top5_export_2024_2025 = df.nlargest(5, '2024/25 Annual')[['Product', '2024/25 Annual']]
print(top5_export_2024_2025)

top5_export_2023_2024_SixMonths = df.nlargest(5, '2023/24 Six Months')[['Product', '2023/24 Six Months']]
print(top5_export_2023_2024_SixMonths)

top5_export_2024_2025_SixMonths = df.nlargest(5, '2024/25 Six Months')[['Product', '2024/25 Six Months']]
print(top5_export_2024_2025_SixMonths)

top5_export_2025_2026_SixMonths = df.nlargest(5, '2025/26 Six Months')[['Product', '2025/26 Six Months']]
print(top5_export_2025_2026_SixMonths)

bottom5 = df.nsmallest(5, '2025/26 Six Months')[['Product', '2025/26 Six Months']]
print(bottom5)

top20 = df.nlargest(20, '2025/26 Six Months')

num_cols = ['2023/24 Six Months', '2024/25 Six Months', '2025/26 Six Months']
df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')

# Reshape for plotly line chart
top5 = df.nlargest(5, '2025/26 Six Months')
df_melted = top5.melt(
    id_vars='Product',
    value_vars=num_cols,
    var_name='Period',
    value_name='Export Value'
)

# Plot
fig = px.line(df_melted, x='Period', y='Export Value',
              color='Product', markers=True,
              title='Six Month Export Trends — Top 5 Commodities')
fig.show()

import matplotlib.pyplot as plt

top5_export_2023_2024.set_index('Product').plot(kind='line', marker='o')
plt.title('Top 5 Exports 2023/24 Annual')
plt.ylabel('Value')
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

print(df.columns.tolist())

df_sorted = df.sort_values(
    by=['2023/24 Annual', '2023/24 Six Months', '2024/25 Annual', '2024/25 Six Months', '2025/26 Six Months'],
    ascending=False
)

df_sorted.head()

Q1 = df['2023/24 Annual'].quantile(0.25)
Q3 = df['2023/24 Annual'].quantile(0.75)
IQR = Q3 - Q1
IQR

df_clean = df[(df['2023/24 Annual'] >= Q1 - 1.5 * IQR) &
              (df['2023/24 Annual'] <= Q3 + 1.5 * IQR)]

df_clean.head()

# Grouped bar — which year exported more?
fig, ax = plt.subplots(figsize=(14, 6))

x = np.arange(len(df))
w = 0.38
ax.bar(x - w/2, df_sorted['2023/24 Annual'], w, label='2024/25', color='#378ADD')
ax.bar(x + w/2, df_sorted['2024/25 Annual'], w, label='2025/26', color='#1D9E75')

ax.set_xticks(x)
ax.set_xticklabels(df_sorted['Product'], rotation=45, ha='right', fontsize=9)
ax.set_title('Annual Chart — Which year exported more?', fontsize=13, fontweight='bold')
ax.set_ylabel('Rs. in million')
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f'{v/1000:.0f}K'))
ax.legend()
ax.spines[['top', 'right']].set_visible(False)
ax.grid(axis='y', linestyle='--', alpha=0.4)

plt.tight_layout()
plt.savefig('chart1_grouped_bar.png', dpi=150, bbox_inches='tight')
plt.show()



fig, ax = plt.subplots(figsize=(14, 6))

x = np.arange(len(top5))
w = 0.26  # narrower width to fit 3 bars

ax.bar(x - w,     top5['2023/24 Six Months'], w, label='2023/24', color='#378ADD')
ax.bar(x,         top5['2024/25 Six Months'], w, label='2024/25', color='#1D9E75')
ax.bar(x + w,     top5['2025/26 Six Months'], w, label='2025/26', color='#5B4FCF')

ax.set_xticks(x)
ax.set_xticklabels(top5['Product'], rotation=45, ha='right', fontsize=9)
ax.set_title('Six Months Chart — Which year exported more?', fontsize=13, fontweight='bold')
ax.set_ylabel('Rs. in million')
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f'{v/1000:.0f}K'))
ax.legend()
ax.spines[['top', 'right']].set_visible(False)
ax.grid(axis='y', linestyle='--', alpha=0.4)

plt.tight_layout()
plt.savefig('chart1_grouped_bar.png', dpi=150, bbox_inches='tight')
plt.show()



import matplotlib.pyplot as plt

top5_export_2023_2024.set_index('Product').plot(kind='line', marker='o')
plt.title('Top 5 Exports 2023/24 Annual')
plt.ylabel('Value')
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt

top5_export_2025_2026_SixMonths.set_index('Product').plot(kind='line', marker='o')
plt.title('Top 5 Exports 2025/26 Annual')
plt.ylabel('Value')
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

cov = df[['2024/25 Growth %', '2025/26 Growth %']].cov().round(2)
print(cov)

cov = df[['2023/24 Six Months', '2024/25 Six Months',
          '2025/26 Six Months']].cov().round(2)
print(cov)



plt.figure(figsize=(10,6))

x = np.arange(len(df2))
w = 0.38

plt.bar(x - w/2, df2['2024/25 Six Months'], w, label='2024/25', color='#378ADD')
plt.bar(x + w/2, df2['2025/26 Six Months'], w, label='2025/26', color='#1D9E75')

plt.xticks(x, df2['Product'], rotation=45, ha='right', fontsize=8)
plt.title('Which year exported more?', fontweight='bold')
plt.ylabel('Rs. in million')
plt.gca().yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f'{v/1000:.0f}K'))

plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.gca().spines[['top', 'right']].set_visible(False)

plt.tight_layout()
plt.show()

plt.figure(figsize=(10,6))

df_rank = df_sorted.sort_values('2025/26 Six Months')

plt.barh(df_rank['Product'], df_rank['2025/26 Six Months'],
         color='#378ADD', height=0.6)

for i, v in enumerate(df_rank['2025/26 Six Months']):
    plt.text(v + 50, i, f'{v/1000:.1f}K', va='center', fontsize=8)

plt.title('Who exports the most?', fontweight='bold')
plt.xlabel('Rs. in million')

plt.grid(axis='x', linestyle='--', alpha=0.4)
plt.gca().spines[['top', 'right']].set_visible(False)

plt.tight_layout()
plt.show()

import plotly.express as px

top5 = df.nlargest(5, '2025/26 Six Months').copy()
others = pd.DataFrame([{
    'Product': 'Others',
    '2025/26 Six Months': df['2025/26 Six Months'].sum() - top5['2025/26 Six Months'].sum()
}])

df_pie = pd.concat([top5, others], ignore_index=True)

fig = px.pie(
    df_pie,
    values='2025/26 Six Months',
    names='Product',
    title='Market Share of Exports —2025/26 Six Months',
    color_discrete_sequence=['red','blue','yellow','green','orange','brown']
)

fig.update_traces(textposition='inside', textinfo='percent+label')
fig.show()

import plotly.express as px

top5 = df.nlargest(5, '2023/24 Annual').copy()
others = pd.DataFrame([{
    'Product': 'Others',
    '2023/24 Annual': df['2023/24 Annual'].sum() - top5['2023/24 Annual'].sum()
}])

df_pie = pd.concat([top5, others], ignore_index=True)

fig = px.pie(
    df_pie,
    values='2023/24 Annual',
    names='Product',
    title='Market Share of Exports —2023/24 Annual',
        color_discrete_sequence=['red','blue','yellow','green','orange','brown']
)

fig.update_traces(textposition='inside', textinfo='percent+label')
fig.show()



import plotly.express as px

top5 = df.nlargest(5, '2024/25 Annual').copy()
others = pd.DataFrame([{
    'Product': 'Others',
    '2024/25 Annual': df['2024/25 Annual'].sum() - top5['2024/25 Annual'].sum()
}])

df_pie = pd.concat([top5, others], ignore_index=True)

fig = px.pie(
    df_pie,
    values='2024/25 Annual',
    names='Product',
    title='Market Share of Exports — 2024/25 Annual',
        color_discrete_sequence=['red','blue','yellow','green','orange','brown']

)

fig.update_traces(textposition='inside', textinfo='percent+label')
fig.show()

df.columns.tolist()